### ISSUE TITLE
Bitcoin Core v25

### ISSUE THREAD

**Issue by Sun0fABeach** [printer-jam/umbrel-ordisrespector#6]
Hi, thanks for the image, I've been running it without any issues. I've been shilling it in the Umbrel forums as well. 
I'd really appreciate if you could provide a version for the v25 release of Bitcoin Core.

Cheers

**Comment by printer-jam** [comment]
I'll have a look at this. 

The image umbrel uses is now: lncm/bitcoind, which is no longer alpine, but linux amd64 based, here: https://hub.docker.com/r/lncm/bitcoind

This means we can't just update the build version in the 24.0.1 Dockerfile because the built binaries won't be compatible.

I'll have to find an amd64 build guide and make a separate Dockerfile for 25.0. Hopefully they stick with the lncm builds and we can just update the version number in the Dockerfile going forward.

Edit: I think the  binaries are compatible, since the new umbrel image is based on lncm, which is what I based the build on here: https://github.com/lukechilds/lncm-docker-bitcoind and is from an alpine image. 

Hopefully won't be too bad.

**Comment by printer-jam** [comment]
@Sun0fABeach 
I updated my umbrel node with the new image built from Dockerfile in the 25.0 folder, feel free to check it out.

**Comment by Sun0fABeach** [comment]
Thanks for putting in the effort. I tried building it on my Umbrel, but it gets stuck at the checksum verification step. Any idea?

![image](https://github.com/printer-jam/umbrel-ordisrespector/assets/8113158/a3833fb6-2561-41a7-9d87-6bdca6d776f5)

**Comment by printer-jam** [comment]
Not sure, that part happens before the patch is even downloaded or applied in the Dockerfile.

Maybe try re-building the image, and if gets stuck again try rebuilding with --no-cache, like `docker build --no-cache ...`

Also you can always try building the Dockerfile somwhere else, and copy the image to your node, but building on the node is the simplest.

**Comment by Sun0fABeach** [comment]
Sorry for the late reply. Unfortunately, building on the Umbrel with `--no-cache`, as well as building on my desktop machine both have the same result. Can't get past that pgp verification step.

**Comment by printer-jam** [comment]
@Sun0fABeach, check your Docker **Server** version. with `docker version`

This is what i've got on the nodes.
```Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
```
I'm willing to bet your version is lower, since I get the same error you have when building on:

```Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
```
Since I'm running ubuntu, I followed the steps here: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
to uninstall the old version of Docker, and install the docker-ce packages on the machine running the 20.10 version of Docker server, and now get:

```Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
```
If after upgrading, you see something like `installed docker-ce package post-installation script subprocess returned error exit status 1` then a `sudo dpkg --configure -a` should fix it.

After upgrading, the machine which couldn't pass the gpg step, same as yours, now on 24.0.2, works a treat.

It is probably a key issue, so if you don't want to upgrade, you can search for a solution, but I think upgrading docker is the easier of the two.

**Comment by Sun0fABeach** [comment]
Ok, I found out what the issue was. I was already on docker version 24.x, but I didn't have the package `docker-buildx` installed. After reinstalling with that extra package, the built went through. (I'm on Manjaro)

Thanks again for putting in the effort. Closing this.
